name: screenshot-api
services:
- name: web
  source_dir: /
  github:
    repo: ossacodes/web-screenshot-api-nodejs
    branch: main
  run_command: npm start
  build_command: npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-s  # At least basic-s for Puppeteer
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
    value: "true"
  - key: PUPPETEER_EXECUTABLE_PATH
    value: "/usr/bin/google-chrome-stable"
