services:
  - type: web
    name: screenshot-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/src/node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/chrome
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: screenshots
      mountPath: /opt/render/project/src/screenshots
      sizeGB: 1
